# Generated by Django 4.2.16 on 2025-07-03 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nepse_index', models.DecimalField(decimal_places=2, help_text='Current value of the NEPSE Index', max_digits=10)),
                ('nepse_index_change', models.DecimalField(blank=True, decimal_places=2, help_text='Change in NEPSE Index from previous close (in points)', max_digits=10, null=True)),
                ('nepse_index_percent_change', models.DecimalField(blank=True, decimal_places=1, help_text='Percentage change in NEPSE Index', max_digits=4, null=True)),
                ('total_market_cap', models.DecimalField(decimal_places=2, help_text='Total market capitalization (in NPR Crores/Billions)', max_digits=8)),
                ('market_cap_change', models.DecimalField(blank=True, decimal_places=1, help_text='Change in total market capitalization (in number)', max_digits=4, null=True)),
                ('market_cap_percent_change', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change in total market capitalization', max_digits=5, null=True)),
                ('volume_traded', models.BigIntegerField(help_text='Total trading volume for the day (number of shares)')),
                ('volume_traded_change', models.BigIntegerField(blank=True, help_text='Change in total trading volume (in number)', null=True)),
                ('volume_traded_percent_change', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change in total trading volume', max_digits=5, null=True)),
                ('gainers_count', models.IntegerField(help_text='Number of stocks that gained value')),
                ('losers_count', models.IntegerField(help_text='Number of stocks that lost value')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update for market overview data')),
            ],
            options={
                'verbose_name': 'Market Overview',
                'verbose_name_plural': 'Market Overviews',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text="Unique ticker symbol of the stock (e.g., 'AAPL', 'NEPSE')", max_length=10, unique=True)),
                ('company_name', models.CharField(help_text="Full name of the company (e.g., 'Apple Inc.')", max_length=255)),
                ('exchange', models.CharField(help_text="Stock exchange where the stock is traded (e.g., 'NASDAQ', 'NEPSE')", max_length=50)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Last traded price of the stock', max_digits=10, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, help_text='Change in price from previous close', max_digits=10, null=True)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change in price', max_digits=5, null=True)),
                ('volume', models.BigIntegerField(blank=True, help_text='Trading volume for the day', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text="Timestamp of the last update to this stock's data")),
                ('description', models.TextField(blank=True, help_text='Brief description or overview of the company', null=True)),
                ('industry', models.CharField(blank=True, help_text='Industry sector the company belongs to', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_date'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last modification to the article'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when the article was published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='A short label for the URL (auto-generated from title)', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', help_text='Publication status of the article', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The user who authored this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(help_text='Full content of the news article'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(help_text='Title of the news article', max_length=255),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short biography of the user', null=True)),
                ('user', models.OneToOneField(help_text='The associated Django User instance', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='related_stocks',
            field=models.ManyToManyField(blank=True, help_text='Stocks mentioned or related to this article', related_name='news_articles', to='news.stock'),
        ),
    ]
